"""
Tests for the this-week.md compile pass.

The actual Claude CLI invocation is mocked — we test the wiring (manifest
building, atomic write, format-validation gate) and not the prompt's
effectiveness against a live LLM.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from plos import compile_this_week


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


@pytest.fixture
def vault(tmp_path: Path) -> Path:
    """Build a tmp vault with one of each entity type plus one dashboard."""
    root = tmp_path / "vault"
    _write(
        root / "source" / "properties" / "123-main-davenport" / "index.md",
        "---\nentity: property\nslug: 123-main-davenport\n"
        "insurance_renewal_date: '2026-05-22'\n---\n# 123 Main\n",
    )
    _write(
        root / "source" / "accounts" / "first-davenport-checking-4521" / "index.md",
        "---\nentity: account\nslug: first-davenport-checking-4521\n---\n"
        "# Checking ...4521\n",
    )
    _write(
        root / "source" / "people" / "joe" / "index.md",
        "---\nentity: person\nslug: joe\n"
        "drivers_license_expiry: '2026-05-15'\n---\n# Joe Sample\n",
    )
    _write(
        root / "dashboards" / "properties.md",
        "---\ntype: dashboard\ndashboard: properties\n---\n# Properties\n",
    )
    return root


VALID_MOCK_RESPONSE = """\
---
type: compiled
artifact: this-week
refreshed: 2026-05-11T12:00:00Z
refresh_cadence: daily
sources_read:
  - /source/people/joe/index.md
  - /source/properties/123-main-davenport/index.md
compile_pass_version: 1
---

# This Week — May 11 – May 17, 2026

## Must do

- **Drivers license expiry — Joe.** Renew before May 15.
  → /source/people/joe/index.md

## Should do

- _(nothing this week)_

## Watching

- **State Farm renewal.** Coming up May 22.
  → /source/properties/123-main-davenport/index.md

---
*Generated by daily compile pass. To regenerate: `compile this-week`.*
"""


# -----------------------------------------------------------------------------
# build_manifest
# -----------------------------------------------------------------------------


def test_build_manifest_includes_all_entity_index_files(vault):
    manifest = compile_this_week.build_manifest(vault)
    assert "/source/properties/123-main-davenport/index.md" in manifest
    assert "/source/accounts/first-davenport-checking-4521/index.md" in manifest
    assert "/source/people/joe/index.md" in manifest


def test_build_manifest_includes_dashboards(vault):
    manifest = compile_this_week.build_manifest(vault)
    assert "/dashboards/properties.md" in manifest


def test_build_manifest_includes_previous_output_if_present(vault):
    _write(vault / "compiled" / "this-week.md", "previous content here")
    manifest = compile_this_week.build_manifest(vault)
    assert "/compiled/this-week.md" in manifest
    assert "previous content here" in manifest


def test_build_manifest_omits_previous_output_when_absent(vault):
    """Bare vault — no previous output exists yet."""
    manifest = compile_this_week.build_manifest(vault)
    assert "Previous compile output" not in manifest


def test_build_manifest_includes_todays_date(vault):
    manifest = compile_this_week.build_manifest(vault)
    # Format: "Today's date (UTC): YYYY-MM-DD"
    assert "Today's date (UTC):" in manifest


# -----------------------------------------------------------------------------
# run() — subprocess wiring
# -----------------------------------------------------------------------------


def test_run_invokes_claude_with_prompt_on_stdin(vault, monkeypatch):
    captured = {}

    def fake_run(cmd, **kwargs):
        captured["cmd"] = cmd
        captured["input"] = kwargs.get("input")
        captured["kwargs"] = kwargs
        return subprocess.CompletedProcess(cmd, 0, VALID_MOCK_RESPONSE, "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    compile_this_week.run(vault)

    assert captured["cmd"][0] == "claude"
    assert "--print" in captured["cmd"]
    # Manifest content reaches the subprocess
    assert "/source/people/joe/index.md" in captured["input"]
    # Preamble reaches the subprocess too
    assert "this-week.md" in captured["input"]
    assert captured["kwargs"]["text"] is True
    assert captured["kwargs"]["check"] is True
    # UTF-8 encoding is required on Windows: both the prompt and
    # Claude's response carry → arrows that cp1252 can't handle.
    assert captured["kwargs"]["encoding"] == "utf-8"


def test_run_writes_claude_output_atomically(vault, monkeypatch):
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(a[0], 0, VALID_MOCK_RESPONSE, ""),
    )
    target = compile_this_week.run(vault)

    assert target == vault / "compiled" / "this-week.md"
    assert target.read_text(encoding="utf-8") == VALID_MOCK_RESPONSE
    # No temp file leak
    leftover = list(target.parent.glob("*.tmp"))
    assert leftover == []


def test_run_overwrites_existing_compiled_output(vault, monkeypatch):
    target = vault / "compiled" / "this-week.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("STALE", encoding="utf-8")

    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(a[0], 0, VALID_MOCK_RESPONSE, ""),
    )
    compile_this_week.run(vault)

    assert target.read_text(encoding="utf-8") == VALID_MOCK_RESPONSE
    assert "STALE" not in target.read_text(encoding="utf-8")


def test_run_rejects_response_without_frontmatter(vault, monkeypatch):
    """Malformed Claude output must not corrupt an existing compiled artifact."""
    target = vault / "compiled" / "this-week.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("EXISTING", encoding="utf-8")

    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(
            a[0], 0, "I can't help with that.", ""
        ),
    )
    with pytest.raises(ValueError, match="frontmatter"):
        compile_this_week.run(vault)

    # Existing file untouched
    assert target.read_text(encoding="utf-8") == "EXISTING"


def test_run_rejects_response_missing_required_sections(vault, monkeypatch):
    """Response with frontmatter but missing 'Must do' must not be written."""
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(
            a[0], 0, "---\ntype: compiled\n---\n# Header only\n", ""
        ),
    )
    with pytest.raises(ValueError, match="Must do"):
        compile_this_week.run(vault)

    assert not (vault / "compiled" / "this-week.md").exists()


def test_run_propagates_subprocess_failure(vault, monkeypatch):
    """If the claude CLI exits non-zero, the run raises and no file is written."""

    def fake_run(cmd, **kwargs):
        raise subprocess.CalledProcessError(1, cmd, "", "claude: not found")

    monkeypatch.setattr(subprocess, "run", fake_run)
    with pytest.raises(subprocess.CalledProcessError):
        compile_this_week.run(vault)

    assert not (vault / "compiled" / "this-week.md").exists()


# -----------------------------------------------------------------------------
# main() / env handling
# -----------------------------------------------------------------------------


def test_resolve_vault_root_requires_env_var(monkeypatch):
    monkeypatch.delenv("PLOS_VAULT_ROOT", raising=False)
    with pytest.raises(RuntimeError, match="PLOS_VAULT_ROOT"):
        compile_this_week._resolve_vault_root()
