"""
Tests for the tax-prep.md compile pass.

The Claude CLI invocation is mocked. We test:
- The inventory-parsing logic (`compute_tax_prep`) end-to-end against
  a temp vault with a real expected-documents.md.
- The wiring (`build_manifest`, `_validate_response`, atomic write,
  inventory-missing short-circuit).

Per CLAUDE.md Phase 5 Slice 3 conventions, the inventory file is the
single source of truth for what's expected vs. received; the
`received: bool` flag is the partitioning signal. Tests reflect that
split: parsing/categorization is exercised against synthetic
inventories; Claude's prose is mocked.
"""

from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

import pytest

from plos import compile_tax_prep


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


@pytest.fixture
def vault(tmp_path: Path) -> Path:
    """Empty vault scaffold; tests seed inventories as needed."""
    root = tmp_path / "vault"
    root.mkdir()
    return root


SAMPLE_INVENTORY = """\
---
type: tax-expected
tax_year: 2026
expected:
  - name: W-2 from Beacon Software
    source: employer
    received: false
    notes: arrives mid-January
  - name: 1098 mortgage interest from Mr. Cooper
    source: mortgage servicer
    received: true
    received_date: 2026-01-28
    received_path: source/tax/2026/received/1098_mr_cooper.pdf
  - name: 1099-INT from First Davenport Bank
    source: bank
    received: false
  - name: Property tax statement (123 Main St)
    source: county assessor
    received: true
    received_date: 2026-04-15
    received_path: source/tax/2026/received/property_tax_2026.pdf
---

# Expected tax documents — 2026

Free-form prose for humans.
"""


VALID_MOCK_RESPONSE = """\
---
type: compiled
artifact: tax-prep
refreshed: 2026-05-10T12:00:00Z
tax_year: 2026
refresh_cadence: monthly (weekly Jan-Apr)
sources_read:
  - /source/tax/2026/expected-documents.md
compile_pass_version: 1
---

# Tax Prep — Tax Year 2026

**Status:** 2 of 4 expected documents received.

## Received

- 1098 mortgage interest from Mr. Cooper. Received 2026-01-28.
  → /source/tax/2026/received/1098_mr_cooper.pdf
- Property tax statement (123 Main St). Received 2026-04-15.
  → /source/tax/2026/received/property_tax_2026.pdf

## Missing

- **W-2 from Beacon Software.** Employer; arrives mid-January.
  → /source/tax/2026/expected-documents.md
- **1099-INT from First Davenport Bank.** Bank.
  → /source/tax/2026/expected-documents.md

---
*Generated by monthly tax-prep compile pass. To regenerate: `compile tax-prep`.*
"""


# -----------------------------------------------------------------------------
# _default_tax_year — calendar math
# -----------------------------------------------------------------------------


def test_default_tax_year_during_filing_window_returns_prior_year():
    """Jan-Apr is the filing window for the previous year."""
    assert compile_tax_prep._default_tax_year(date(2026, 1, 5)) == 2025
    assert compile_tax_prep._default_tax_year(date(2026, 4, 15)) == 2025
    assert compile_tax_prep._default_tax_year(date(2026, 4, 30)) == 2025


def test_default_tax_year_outside_filing_window_returns_current_year():
    """May-Dec is the collection window for the current year."""
    assert compile_tax_prep._default_tax_year(date(2026, 5, 1)) == 2026
    assert compile_tax_prep._default_tax_year(date(2026, 12, 31)) == 2026


# -----------------------------------------------------------------------------
# compute_tax_prep — parsing + categorization
# -----------------------------------------------------------------------------


def test_compute_tax_prep_returns_none_when_inventory_missing(vault):
    """No file at source/tax/<year>/expected-documents.md → None."""
    assert (
        compile_tax_prep.compute_tax_prep(vault, tax_year=2026) is None
    )


def test_compute_tax_prep_partitions_received_vs_missing(vault):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    assert result is not None
    assert result.tax_year == 2026
    assert len(result.received) == 2
    assert len(result.missing) == 2

    received_names = [d.name for d in result.received]
    assert "1098 mortgage interest from Mr. Cooper" in received_names
    assert "Property tax statement (123 Main St)" in received_names

    missing_names = [d.name for d in result.missing]
    assert "W-2 from Beacon Software" in missing_names
    assert "1099-INT from First Davenport Bank" in missing_names


def test_compute_tax_prep_preserves_entry_metadata(vault):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    assert result is not None

    cooper = next(d for d in result.received if "Mr. Cooper" in d.name)
    assert cooper.source == "mortgage servicer"
    assert cooper.received_date == "2026-01-28"
    assert cooper.received_path == "source/tax/2026/received/1098_mr_cooper.pdf"

    w2 = next(d for d in result.missing if "W-2" in d.name)
    assert w2.source == "employer"
    assert w2.received is False
    assert w2.notes == "arrives mid-January"
    assert w2.received_date is None
    assert w2.received_path is None


def test_compute_tax_prep_empty_expected_list_returns_empty_lists(vault):
    """An inventory file with `expected: []` is a valid empty inventory."""
    _write(
        vault / "source" / "tax" / "2026" / "expected-documents.md",
        "---\ntype: tax-expected\ntax_year: 2026\nexpected: []\n---\n\n# 2026\n",
    )
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    assert result is not None
    assert result.received == []
    assert result.missing == []


def test_compute_tax_prep_skips_non_dict_entries(vault):
    """A scalar (e.g. just a string) in the `expected:` list is ignored."""
    _write(
        vault / "source" / "tax" / "2026" / "expected-documents.md",
        "---\nexpected:\n  - W-2\n  - {name: 1099, received: true}\n---\n",
    )
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    assert result is not None
    # Only the dict entry lands
    assert len(result.received) == 1
    assert len(result.missing) == 0
    assert result.received[0].name == "1099"


def test_compute_tax_prep_treats_missing_received_flag_as_false(vault):
    """An entry with no `received:` key is treated as missing."""
    _write(
        vault / "source" / "tax" / "2026" / "expected-documents.md",
        "---\nexpected:\n  - name: W-2\n  - {name: 1099, received: true}\n---\n",
    )
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    assert result is not None
    assert len(result.received) == 1
    assert len(result.missing) == 1
    assert result.missing[0].name == "W-2"


def test_compute_tax_prep_uses_default_year_from_as_of(vault):
    """Resolves tax_year from as_of when caller passes neither."""
    _write(vault / "source" / "tax" / "2025" / "expected-documents.md", SAMPLE_INVENTORY)
    # February 2026 → filing window for 2025
    result = compile_tax_prep.compute_tax_prep(vault, as_of=date(2026, 2, 1))
    assert result is not None
    assert result.tax_year == 2025


def test_compute_tax_prep_explicit_tax_year_overrides_as_of(vault):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    # February 2026 would default to 2025, but explicit override wins.
    result = compile_tax_prep.compute_tax_prep(
        vault, tax_year=2026, as_of=date(2026, 2, 1)
    )
    assert result is not None
    assert result.tax_year == 2026


# -----------------------------------------------------------------------------
# build_manifest
# -----------------------------------------------------------------------------


def test_build_manifest_includes_counts_and_year(vault):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    manifest = compile_tax_prep.build_manifest(vault, result)
    assert "Tax year: 2026" in manifest
    assert "Received count: 2" in manifest
    assert "Missing count: 2" in manifest
    assert "Total count: 4" in manifest


def test_build_manifest_renders_both_lists_with_entry_metadata(vault):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    manifest = compile_tax_prep.build_manifest(vault, result)
    assert "## Received entries" in manifest
    assert "## Missing entries" in manifest
    assert "name: 1098 mortgage interest from Mr. Cooper" in manifest
    assert "received_path: /source/tax/2026/received/1098_mr_cooper.pdf" in manifest
    assert "notes: arrives mid-January" in manifest
    # Inventory file is bundled as provenance
    assert "/source/tax/2026/expected-documents.md" in manifest
    assert "type: tax-expected" in manifest


def test_build_manifest_renders_empty_lists_with_marker(vault):
    _write(
        vault / "source" / "tax" / "2026" / "expected-documents.md",
        "---\nexpected: []\n---\n",
    )
    result = compile_tax_prep.compute_tax_prep(vault, tax_year=2026)
    manifest = compile_tax_prep.build_manifest(vault, result)
    assert "Received count: 0" in manifest
    assert "Missing count: 0" in manifest
    # Each empty section heading gets a `_(none)_` marker
    assert manifest.count("_(none)_") == 2


# -----------------------------------------------------------------------------
# _validate_response
# -----------------------------------------------------------------------------


def test_validate_response_accepts_valid_artifact():
    compile_tax_prep._validate_response(VALID_MOCK_RESPONSE)


def test_validate_response_rejects_missing_frontmatter():
    with pytest.raises(ValueError, match="frontmatter"):
        compile_tax_prep._validate_response("Sure, here you go.")


def test_validate_response_rejects_missing_received_heading():
    response = (
        "---\ntype: compiled\nartifact: tax-prep\n---\n\n"
        "# Tax Prep — Tax Year 2026\n\n## Missing\n- x\n"
    )
    with pytest.raises(ValueError, match="Received"):
        compile_tax_prep._validate_response(response)


def test_validate_response_rejects_missing_missing_heading():
    response = (
        "---\ntype: compiled\nartifact: tax-prep\n---\n\n"
        "# Tax Prep — Tax Year 2026\n\n## Received\n- x\n"
    )
    with pytest.raises(ValueError, match="Missing"):
        compile_tax_prep._validate_response(response)


# -----------------------------------------------------------------------------
# run — inventory-missing short-circuit
# -----------------------------------------------------------------------------


def test_run_short_circuits_when_no_inventory_file(vault, monkeypatch):
    """No inventory → write deterministic 'no inventory configured' artifact."""

    def fake_run(*args, **kwargs):
        raise AssertionError(
            "subprocess.run must not be invoked when inventory is missing"
        )

    monkeypatch.setattr(subprocess, "run", fake_run)
    target = compile_tax_prep.run(vault, tax_year=2026)

    body = target.read_text(encoding="utf-8")
    assert body.startswith("---\n")
    assert "artifact: tax-prep" in body
    assert "tax_year: 2026" in body
    assert "## Received" in body
    assert "## Missing" in body
    assert "no inventory configured" in body.lower()
    # Atomic write leaves no temp file
    assert list(target.parent.glob("*.tmp")) == []


# -----------------------------------------------------------------------------
# run — non-empty path invokes claude
# -----------------------------------------------------------------------------


def test_run_invokes_claude_with_utf8_encoding(vault, monkeypatch):
    """The Windows cp1252 trap fixed in 69b9e62 must not regress here."""
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    captured = {}

    def fake_run(cmd, **kwargs):
        captured["cmd"] = cmd
        captured["kwargs"] = kwargs
        captured["input"] = kwargs.get("input")
        return subprocess.CompletedProcess(cmd, 0, VALID_MOCK_RESPONSE, "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    compile_tax_prep.run(vault, tax_year=2026)

    assert captured["cmd"][0] == "claude"
    assert "--print" in captured["cmd"]
    assert captured["kwargs"]["check"] is True
    assert captured["kwargs"]["text"] is True
    assert captured["kwargs"]["encoding"] == "utf-8"
    # Manifest + categorization data reach the subprocess
    assert "Received count: 2" in captured["input"]
    assert "Missing count: 2" in captured["input"]


def test_run_writes_response_atomically(vault, monkeypatch):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(a[0], 0, VALID_MOCK_RESPONSE, ""),
    )
    target = compile_tax_prep.run(vault, tax_year=2026)
    assert target == vault / "compiled" / "tax-prep.md"
    assert target.read_text(encoding="utf-8") == VALID_MOCK_RESPONSE
    assert list(target.parent.glob("*.tmp")) == []


def test_run_preserves_existing_on_invalid_response(vault, monkeypatch):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)
    target = vault / "compiled" / "tax-prep.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("EXISTING", encoding="utf-8")

    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *a, **kw: subprocess.CompletedProcess(
            a[0], 0, "I can't help with that.", ""
        ),
    )
    with pytest.raises(ValueError, match="frontmatter"):
        compile_tax_prep.run(vault, tax_year=2026)
    assert target.read_text(encoding="utf-8") == "EXISTING"


def test_run_propagates_subprocess_failure(vault, monkeypatch):
    _write(vault / "source" / "tax" / "2026" / "expected-documents.md", SAMPLE_INVENTORY)

    def fake_run(cmd, **kwargs):
        raise subprocess.CalledProcessError(1, cmd, "", "claude: not found")

    monkeypatch.setattr(subprocess, "run", fake_run)
    with pytest.raises(subprocess.CalledProcessError):
        compile_tax_prep.run(vault, tax_year=2026)
    assert not (vault / "compiled" / "tax-prep.md").exists()


# -----------------------------------------------------------------------------
# Env handling
# -----------------------------------------------------------------------------


def test_resolve_vault_root_requires_env_var(monkeypatch):
    monkeypatch.delenv("PLOS_VAULT_ROOT", raising=False)
    with pytest.raises(RuntimeError, match="PLOS_VAULT_ROOT"):
        compile_tax_prep._resolve_vault_root()


def test_resolve_tax_year_defaults_to_none_when_unset(monkeypatch):
    monkeypatch.delenv(compile_tax_prep.TAX_YEAR_ENV_VAR, raising=False)
    assert compile_tax_prep._resolve_tax_year() is None


def test_resolve_tax_year_parses_int(monkeypatch):
    monkeypatch.setenv(compile_tax_prep.TAX_YEAR_ENV_VAR, "2025")
    assert compile_tax_prep._resolve_tax_year() == 2025


def test_resolve_tax_year_raises_on_malformed(monkeypatch):
    monkeypatch.setenv(compile_tax_prep.TAX_YEAR_ENV_VAR, "twenty-six")
    with pytest.raises(ValueError):
        compile_tax_prep._resolve_tax_year()
