"""
Compile pass for `compiled/this-week.md`.

The first compiled artifact in PLOS. Builds a manifest of the vault's
current state — every entity index.md, every dashboard, the previous
this-week.md if any — and shells out to the Claude Code CLI to render
a fresh `compiled/this-week.md` per the format spec in
`docs/artifact-templates.md`.

Per ARCHITECTURE.md design principle: "Free local extractors handle
the hot path; AI handles the long tail." Compile passes are the long
tail — they need synthesis beyond aggregation, and they're the right
place to spend Claude Code subscription tokens.

Per CONVENTIONS.md routing rule, this artifact exists because the
question "What needs my attention this week?" requires priority
reasoning across domains, which Dataview cannot provide.

Atomic-write discipline matches `vault.merge_frontmatter`: write to a
sibling temp file, fsync, rename. A reader opening the artifact during
regeneration sees the previous version or the new version — never a
half-written file.

Format-validation gate: if Claude returns content that doesn't start
with the YAML frontmatter delimiter or is missing the four expected
section headings, the run raises and the existing file is preserved.
The compile pass refuses to corrupt the artifact even if the AI
misbehaves.

Run from the repo root:
    python -m plos.compile_this_week
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

logger = logging.getLogger("plos.compile_this_week")

ARTIFACT_PATH = Path("compiled/this-week.md")
REQUIRED_SECTIONS = (
    "## Must do",
    "## Should do",
    "## Watching",
)


PROMPT_PREAMBLE = """\
You are the compile pass for `compiled/this-week.md` in the PLOS
(Personal Life Operating System) vault. Your job: produce a fresh
`this-week.md` markdown file that answers the cross-cutting question
"What needs my attention this week?" by reasoning across the entity
records and dashboards in the manifest below.

Output format — match this shape exactly:

```
---
type: compiled
artifact: this-week
refreshed: <ISO-8601 UTC timestamp you set to right now>
refresh_cadence: daily
sources_read:
  - <every /source/... or /dashboards/... path you cite below>
compile_pass_version: 1
---

# This Week — <Mon DD> – <Mon DD>, <YYYY>

## Must do

- **<bold one-line title>.** <plain-language sentence about what to do
  and why now>.
  → /source/...

## Should do

- ...

## Watching

- ...

## Birthdays / dates this week

- <Mon DD> — <plain-language note>.

---
*Generated by daily compile pass. To regenerate: `compile this-week`.*
```

Section conventions:

- **Must do**: dated obligations within the next 7 days that have
  consequences if missed (renewals expiring, payments due, IDs
  expiring).
- **Should do**: dated items 8-21 days out, or recurring obligations
  approaching their typical cycle.
- **Watching**: items without a hard date but worth tracking (anomalies,
  gaps, things drifting).
- **Birthdays / dates this week**: birthdays and anniversaries inside
  a 7-day window. If none, omit the section heading and contents.

Provenance rules:

- Every claim cites the source path it came from with a `→ /source/...`
  arrow on its own line under the bullet. Use the path as it appears
  in the manifest.
- The `sources_read:` frontmatter list must include every path you
  cite. Include only paths you actually cite — not the entire vault.
- If the manifest contains a `dashboards/<name>.md` you reference, cite
  it as `→ /dashboards/<name>.md`.

Other rules:

- Date math: today's date is given at the top of the manifest. Use it.
- "This week" runs from today through 7 days out for the title.
- Keep bullets to 1-2 sentences; the goal is action, not narrative.
- If a section has no items, write `- _(nothing this week)_` so the
  reader knows it was considered.
- Do not include any commentary, explanation, or code fences around
  the document. Emit the markdown only — your response must be
  copy-pasted directly into `this-week.md` with no edits.

Manifest follows.

"""


PROMPT_INSTRUCTION = """

Now produce the rendered `this-week.md` document. Output the markdown
directly — no commentary, no preamble, no closing remarks. The first
character of your response must be the opening `---` of the YAML
frontmatter; the last character must be the final newline of the
footer.
"""


def _read_text(path: Path) -> str:
    """Read a file as UTF-8 text."""
    return path.read_text(encoding="utf-8")


def _vault_relative(path: Path, vault_root: Path) -> str:
    """Render an in-vault path as `/source/...` for the manifest."""
    rel = path.resolve().relative_to(vault_root.resolve())
    return "/" + str(rel).replace("\\", "/")


def build_manifest(vault_root: Path) -> str:
    """Return the markdown blob the compile pass feeds to Claude.

    Bundles today's date, every entity index.md, every dashboard, and
    the previous compiled output (if any) into a single string.
    """
    today = datetime.now(timezone.utc).date().isoformat()
    parts: list[str] = [f"# Manifest\n\nToday's date (UTC): {today}\n"]

    # Entity records
    source_root = vault_root / "source"
    if source_root.is_dir():
        for index_path in sorted(source_root.glob("*/*/index.md")):
            rel = _vault_relative(index_path, vault_root)
            parts.append(f"\n## {rel}\n\n```markdown\n{_read_text(index_path)}\n```\n")

    # Dashboards
    dashboards_root = vault_root / "dashboards"
    if dashboards_root.is_dir():
        for dash_path in sorted(dashboards_root.glob("*.md")):
            rel = _vault_relative(dash_path, vault_root)
            parts.append(f"\n## {rel}\n\n```markdown\n{_read_text(dash_path)}\n```\n")

    # Previous compiled output (if present) — for delta context
    previous = vault_root / ARTIFACT_PATH
    if previous.is_file():
        parts.append(
            f"\n## Previous compile output ({_vault_relative(previous, vault_root)})\n\n"
            f"```markdown\n{_read_text(previous)}\n```\n"
        )

    return "".join(parts)


def _validate_response(response: str) -> None:
    """Raise if the Claude response doesn't look like a valid this-week.md."""
    stripped = response.lstrip("﻿").lstrip()
    if not stripped.startswith("---"):
        raise ValueError(
            "compile_this_week: response does not start with YAML frontmatter "
            "delimiter (---); refusing to write."
        )
    for heading in REQUIRED_SECTIONS:
        if heading not in response:
            raise ValueError(
                f"compile_this_week: response missing required section heading "
                f"{heading!r}; refusing to write."
            )


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path via temp+rename. Mirrors vault.merge_frontmatter."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def run(vault_root: Path, claude_cmd: str = "claude") -> Path:
    """Build manifest, invoke Claude CLI, atomically write the artifact.

    Returns the path written. Raises on subprocess failure or invalid
    response — in either case the existing file (if any) is preserved.
    """
    manifest = build_manifest(vault_root)
    prompt = PROMPT_PREAMBLE + manifest + PROMPT_INSTRUCTION

    logger.info(
        "invoking %s --print (manifest length: %d chars)", claude_cmd, len(manifest)
    )
    # encoding="utf-8" is non-negotiable on Windows — both the prompt
    # (with → source-provenance arrows) and Claude's response contain
    # non-ASCII characters that the default cp1252 codec can't handle.
    completed = subprocess.run(
        [claude_cmd, "--print"],
        input=prompt,
        capture_output=True,
        text=True,
        check=True,
        encoding="utf-8",
    )
    response = completed.stdout

    _validate_response(response)

    target = vault_root / ARTIFACT_PATH
    _atomic_write(target, response)
    logger.info("wrote %s (%d bytes)", target, len(response))
    return target


def _resolve_vault_root() -> Path:
    """Pull PLOS_VAULT_ROOT from env. Same shape as worker._resolve_vault_root."""
    raw = os.environ.get("PLOS_VAULT_ROOT")
    if not raw:
        raise RuntimeError("PLOS_VAULT_ROOT not set in environment")
    p = Path(raw)
    if not p.is_absolute():
        p = Path.cwd() / p
    return p.resolve()


def main() -> None:
    load_dotenv()
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
        stream=sys.stdout,
    )
    vault_root = _resolve_vault_root()
    target = run(vault_root)
    logger.info("compile this-week complete: %s", target)


if __name__ == "__main__":
    main()
